version: "3"

services:
  zxinfo-es-v8:
    build:
      context: ./elastic-8.17.0-alpine/
    ports:
      - "9400:9200"
      - "9500:9300"

  zxinfo-api-v5:
    environment:
      - NODE_ENV=production
    build:
      context: ./
    restart: on-failure
    ports:
      - "8400:3000"
    links:
      - zxinfo-es-v8
